# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.comboBox_test = QtWidgets.QComboBox(Form)
        self.comboBox_test.setGeometry(QtCore.QRect(50, 60, 69, 22))
        self.comboBox_test.setObjectName("comboBox_test")
        self.comboBox_test.addItem("")
        self.comboBox_test.addItem("")
        self.comboBox_test.addItem("")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.comboBox_test.setItemText(0, _translate("Form", "aaa"))
        self.comboBox_test.setItemText(1, _translate("Form", "bbb"))
        self.comboBox_test.setItemText(2, _translate("Form", "ccc"))
